### ISSUE TITLE
add all sudo users to the adm group too

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habcloud-salt-states#4]
...thereby allowing access to log files without having to sudo all the time.

**Comment by adamgreig** [comment]
We should remove sudo from ssh's allowgroups, leaving it as just users, then have it add sudo members to both users and adm. The method I already have for adding sudo members to users only works if there's a users group in pillar (it can be empty), so we should find a way to deal with that too.

**Comment by adamgreig** [comment]
closed properly in https://github.com/ukhas/habcloud-salt-states/commit/5b654d6eb0df9884f109e8a09eb289440683d348
