### ISSUE TITLE
update ceto/phorcys salt master config

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habcloud-salt-states#7]
- [x] to use salt.vm as the master
- [x] and document this in bootstrapping.

**Comment by adamgreig** [comment]
Closed by https://github.com/ukhas/habcloud-infra/commit/660b4fd578ecf83b85b0a20280d2434a2614b547 and https://github.com/ukhas/habcloud-infra/commit/2d5a7750e229b3b8e4edb0fdc13b53c21dc05a89
